# Generated by Django 4.1.1 on 2022-09-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orders_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='dateTime',
            new_name='date_time',
        ),
    ]
